version: '3.3'
services:
  cassandra:
    container_name: cassandra
    image: cassandra:3
    ports:
      - 9042:9042
    volumes:
      - cassandra-storage:/var/lib/cassandra/
      - ../../../cql/LOCAL_USE_ONLY:/tmp/LOCAL_USE_ONLY

  kafka:
    container_name: kafka_cde
    image: wurstmeister/kafka:2.11-1.1.0 # Production version of kafka 1.1.0
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=192.168.99.100
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    command: bash -c "sleep 10 && start-kafka.sh"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  zookeeper:
    container_name: zookeeper_cde
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

volumes:
  cassandra-storage:

networks:
  cde_default:
    external:
      name: cassandra-network

#CREATE keyspace test with replication = {'class': 'SimpleStrategy', 'replication_factor':1};
#  CREATE TABLE IF NOT EXISTS even
#  (
#  id uuid,
#  key text,
#  msg_value text,
#  indx int,
#  PRIMARY KEY (id)
#  );
#
#  CREATE TABLE IF NOT EXISTS odd
#  (
#  id uuid,
#  key text,
#  msg_value text,
#  indx int,
#  PRIMARY KEY (id)
#  );